### ISSUE TITLE
DataFetcher stops fetching after first error

### ISSUE THREAD

**Issue by scvalex** [mssantos/covid19-atw#1]
`DataFetcher` stops fetching after the first error.  I think you need a `schedule_fetch` in the error case.

https://github.com/mssantos/covid19-atw/blob/bd04dad8f06df21bbcb610bb21a328d133c7458d/lib/covid19/data_fetcher.ex#L47

**Comment by mssantos** [comment]
Thanks for pointing that out, @scvalex . I’ve just fixed it on f72a6fac0caedb14fcc0fc902d98be1483adfafe.

**Comment by scvalex** [comment]
Cheers.
